name: Deploy Frontend to EC2

on:
  push:
    branches: [main]
    paths:
      - 'aws-datavalidator/src/**'
      - 'aws-datavalidator/public/**'
      - 'aws-datavalidator/package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.JUMP_HOST }}
          proxy_username: ${{ secrets.JUMP_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Tube-Project
            git pull origin main
            cd aws-datavalidator
            npm install
            npm run build
